/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "encoder.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ENCODER_DATA, encoder_data_t, AUTO)




