/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "imu.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GYRO_DATA, gyro_data_t, AUTO)


PB_BIND(ACCEL_DATA, accel_data_t, AUTO)


PB_BIND(TELEMETRY, telemetry_t, AUTO)



