/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "imu.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(IMU_GYRO_DATA, imu_gyro_data_t, AUTO)


PB_BIND(IMU_ACCEL_DATA, imu_accel_data_t, AUTO)


PB_BIND(IMU_TELEMETRY, imu_telemetry_t, AUTO)



