/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MOTOR_MOTOR_PB_H_INCLUDED
#define PB_MOTOR_MOTOR_PB_H_INCLUDED
#include "../nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct motor_motor_target {
    float target_position;
    float amplitude;
    float frequency;
} motor_motor_target_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MOTOR_MOTOR_TARGET_INIT_DEFAULT          {0, 0, 0}
#define MOTOR_MOTOR_TARGET_INIT_ZERO             {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MOTOR_MOTOR_TARGET_TARGET_POSITION_TAG   1
#define MOTOR_MOTOR_TARGET_AMPLITUDE_TAG         2
#define MOTOR_MOTOR_TARGET_FREQUENCY_TAG         3

/* Struct field encoding specification for nanopb */
#define MOTOR_MOTOR_TARGET_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    target_position,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    amplitude,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    frequency,         3)
#define MOTOR_MOTOR_TARGET_CALLBACK NULL
#define MOTOR_MOTOR_TARGET_DEFAULT NULL

extern const pb_msgdesc_t motor_motor_target_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MOTOR_MOTOR_TARGET_FIELDS &motor_motor_target_t_msg

/* Maximum encoded size of messages (where known) */
#define MOTOR_MOTOR_PB_H_MAX_SIZE                MOTOR_MOTOR_TARGET_SIZE
#define MOTOR_MOTOR_TARGET_SIZE                  15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
